[workspace]
members = [
    "rmcs-auth-api/rust",
    "rmcs-auth-db",
    "rmcs-resource-api/rust",
    "rmcs-resource-db",
    "rmcs-api-server",
    "rmcs-api-client/rust",
]
resolver = "2"

[profile.release]
opt-level = "s"
