version: '3'

services:

  combined-db:
    image: postgres_multidb:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=db_P4s5w0rd
      - POSTGRES_MULTIPLE_DATABASES=rmcs_auth,rmcs_resource
    volumes:
      - combined-data:/var/lib/postgresql/data
    restart: unless-stopped

  combined-server:
    image: combined_server:0.1.0
    ports:
      - 9001:9001
      - 9002:9002
    environment:
      - DATABASE_URL_AUTH=postgres://postgres:db_P4s5w0rd@combined-db/rmcs_auth
      - DATABASE_URL_RESOURCE=postgres://postgres:db_P4s5w0rd@combined-db/rmcs_resource
      - BIND_ADDRESS_AUTH=0.0.0.0:9001
      - BIND_ADDRESS_RESOURCE=0.0.0.0:9002
      - SERVER_ADDRESS_AUTH=http://127.0.0.1:9001
      - ROOT_PASSWORD=r0ot_P4s5w0rd
      - ROOT_ACCESS_DURATION=300
      - ROOT_REFRESH_DURATION=3600
      - API_ID=00000000-0000-0000-0000-000000000000
      - API_PASSWORD=Ap1_P4s5w0rd
    depends_on:
      - combined-db
    restart: unless-stopped

volumes:

  combined-data:
    driver: local
